# Generated by Django 5.0.6 on 2024-07-10 18:47

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dest_dir",
                    models.CharField(
                        help_text="Default directory for exported articles.",
                        max_length=255,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="", help_text="Site name", max_length=255),
                ),
                (
                    "site_headline",
                    models.CharField(
                        default="", help_text="Site headline", max_length=255
                    ),
                ),
                (
                    "site_teaser",
                    models.CharField(
                        default="", help_text="Site teaser", max_length=255
                    ),
                ),
                ("about", django_quill.fields.QuillField()),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "usercontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.usercontent",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                ("display_order", models.IntegerField()),
            ],
            bases=("cms.usercontent",),
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "usercontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.usercontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonials",
                "verbose_name_plural": "Testimonials",
            },
            bases=("cms.usercontent", models.Model),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "usercontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.usercontent",
                    ),
                ),
                ("title", models.TextField()),
                ("teaser", models.CharField(blank=True, max_length=1000, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
            },
            bases=("cms.usercontent",),
        ),
    ]
