# Generated by Django 5.0.6 on 2024-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
