# Generated by Django 5.0.6 on 2024-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_teammember_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
