# Generated by Django 5.0.6 on 2024-07-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_alter_teammember_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="headline_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
